[package]
name = "grundlagen_raumfahrt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ode_solvers = "0.3.7"
plotters = "0.3.5"
transpose = "0.2.2"
itertools = "0.12.0"
csv = "1.3.0"
